import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/gabriel-pitrella.png"
import AnimatedText from '@/components/AnimtedText'
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className='pt-0 md:p-16 sm:pt-8'>
          <div className="flex flex-col items-left justify-between w-full lg:flex-col lg:items-center md:items-center">
            <div className='w-max md:self-center flex flex-row content-center gap-2.5'>
              <Image
                src={profilePic}
                alt="Gabriel Pitrella"
                className='w-16 h-16 rounded-full lg:w-12 lg:h-12' 
                priority
                sizes="(max-width:768px) 10vw, (max-width: 1200px) 5vw, 5vw"
              />
              <AnimatedText
                text="Software Engineer Full Stack"
                className='!text-lg !text-left md:ttext-lg'
              />
            </div>
            <div className='w-full flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText
                text="Developing Solutions"
                className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl'
              />
              <p className='my-4 text-base font-medium dark:text-light md:text-sm sm:text-xs'>
                Software Engineer Full Stack with over 4 years of hands-on expertise in crafting and implementing 
                efficient solutions using diverse technologies, including JavaScript, TypeScript, NodeJS, ReactJS, 
                Express, PostgreSQL, MongoDB and more.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="\GabrielPitrella_CV-SoftwareEngineer.pdf" target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-2 rounded-lg text-lg font-semibold
                  hover:bg-light hover:text-dark border-2 border-transparent hover:border-dark
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  CV <LinkArrow className="w-4 ml-1" />
                </Link>
                <Link href="mailto:gabrielpitrella@gmail.com" target="_blank"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Contact me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
        <HireMe />
        <div className='absolute right-10 bottom-0 inline-block w-20 md:hidden'>
          <Image src={lightBulb} alt="Light Bulb" className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
